name: Auto Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy file to dev server
        if: github.ref == 'refs/heads/dev'
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.SSH_HOST }}'
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          local_path: './*'
          remote_path: '${{ secrets.DEPLOY_DEV_PATH }}'
          args: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'

      - name: Deploy file to prod server
        if: github.ref == 'refs/heads/master'
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.SSH_HOST }}'
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          local_path: './*'
          remote_path: '${{ secrets.DEPLOY_PROD_PATH }}'
          args: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'
