name: Auto Deploy

on:
  push:
    branches:
      - master #推送master分支,部署到生产服务器
      - dev #推送dev分支,部署到开发服务器

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file to dev server
        if: github.ref == 'refs/heads/dev' #对分支进行检测
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets. }}'
          server: '${{ secrets.IP }}' #服务器地址
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          local_path: './*'
          remote_path: '${{ secrets.DEPLOY_DEV_PATH }}' #测试服务器部署路径

      - name: deploy file to prod server
        if: github.ref == 'refs/heads/master' #对分支进行检测
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets. }}'
          server: '${{ secrets.IP }}' #服务器地址
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          local_path: './*'
          remote_path: '${{ secrets.DEPLOY_PROD_PATH }}' #服务器部署路径
