name: Test

on:
  push:
    branches:
      - master

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test my actions
        #if: github.ref == 'refs/heads/master'
        uses: llxlr/fuck-deploy@master
        with:
          type: 'password'
          username: 'root'
          host: '127.0.0.1'
          port: 22
          password: '123456'
          local_path: './*'
          remote_path: '/www/wwwroot/test/'
